# Auth settings
security:
    oauth2:
        client:
            clientId: ${apgw_client_id}
            clientSecret: ${apgw_client_secret}
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile,email
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false

# H2
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: test
    password: test123
    driver-class-name: org.h2.Driver

# server settings
server:
    address: 0.0.0.0

# File storage
file-path: ${HOME} # change this  to store files elsewhere