package com.example.apgw.model;

import com.fasterxml.jackson.annotation.JsonBackReference;
import lombok.Getter;
import lombok.Setter;

import javax.persistence.*;
import java.io.Serializable;

@Entity
@IdClass(StudentSubjectId.class)
@Getter
@Setter
public class StudentSubject implements Serializable {

    //Primary keys
    @Id
    @Column(name = "subject_id")
    Long subjectId;
    @Id
    @Column(name = "student_email")
    String studentEmail;

    String uid;   //eg. Roll No
    @ManyToOne
    @JsonBackReference
    @JoinColumn(name = "subject_id", insertable = false, updatable = false)
    private Subject subject;
    @ManyToOne
    @JsonBackReference
    @JoinColumn(name = "student_email", insertable = false, updatable = false)
    private Student student;

    /**
     * Constructor for StudentSubject Entity.
     * Gives relation between student and subject,
     * includes uid unique for the combination of subject and student.
     *
     * @param subjectId    AutoGenerated id of subject
     * @param studentEmail Email of student
     * @param uid          User id of student. Eg. Roll No
     */
    public StudentSubject(Long subjectId, String studentEmail, String uid) {
        this.subjectId = subjectId;
        this.studentEmail = studentEmail;
        this.uid = uid;
    }

    public StudentSubject() {
    }
}
